### ISSUE TITLE
Online documentation build failed

### ISSUE THREAD

**Issue by vbdr** [jorge-ramirez-upm/RepTate#146]
Error from Readthedocs:

```
Running Sphinx v3.0.4

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/docs/source/conf.py", line 26, in <module>
    import RepTate
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/__init__.py", line 7, in <module>
    from RepTate.core.CmdBase import CmdBase, CmdMode
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/core/CmdBase.py", line 45, in <module>
    from colorama import Fore, init
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 218, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 174, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 332, in eval_config_file
    raise ConfigError(msg % traceback.format_exc())
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/docs/source/conf.py", line 26, in <module>
    import RepTate
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/__init__.py", line 7, in <module>
    from RepTate.core.CmdBase import CmdBase, CmdMode
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/core/CmdBase.py", line 45, in <module>
    from colorama import Fore, init
ModuleNotFoundError: No module named 'colorama'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 319, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/docs/source/conf.py", line 26, in <module>
    import RepTate
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/__init__.py", line 7, in <module>
    from RepTate.core.CmdBase import CmdBase, CmdMode
  File "/home/docs/checkouts/readthedocs.org/user_builds/reptate/checkouts/latest/RepTate/core/CmdBase.py", line 45, in <module>
    from colorama import Fore, init
ModuleNotFoundError: No module named 'colorama'
```

**Comment by vbdr** [comment]
Fixed in commit cc270d4
